---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины. 
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины и продолжить выбирать товары в каталоге.
  - Пользователь может оформить заказ с переходом на страницу оплаты.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен хранить корзину в сессии браузера.
implicit:
  - Пользователь должен иметь возможность фильтровать товар по производителю и наличию.
  - Пользователь должен иметь возможность переключать язык всего текста на сайте.
  - Пользователь не должен иметь возможность добавлять в корзину товара больше, чем есть в наличии.
  - Если фильтр товара не выбран, на странице должен быть отображен весь список товаров магазина.
  - Должно работать корректное переключение страниц каталога товаров.
