---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины. 
 - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность фильтровать товар по производителю и наличию.
  - Пользователь должен иметь возможность переключать язык текста на сайте.
  - Пользователь не должен иметь возможность добавлять в корзину товара больше, чем есть в наличии.
  - При добавлении товара в корзину, пользователь должен получить уведомление о том, что товар добавлен в корзину.
  - Если фильтр товара не выбран, на странице должен быть отображен весь список товаров магазина.
  - Должен отображаться корректный список фильтров.
  - Должно работать корректное переключение страниц.
  - В карточке товара должна быть кнопка "назад", чтобы вернуться к каталогу.
  - При переключении языка, должен переводиться весь текст на сайте.
  
 

